const sheepledata = [
  "Which large animal would make the best pet if it was tiny?",
  "If you were a pet, what kind would you want to be?",
  "What is the worst possible pet to have?",
  "What is the most intriguing fictional creature?",
  "If any fictional creature could be made real, which one should we choose?",
  "Which fictional creature would be best to ride on?",
  "What is the most beautiful creature? (or strangest, greediest, cuddliest, most intelligent etc.) ",
  "If you could safely ride any animal, which would it be?",
  "If you could become an animal, which would you choose?",
  "Where is a good place for a picnic (or a swim, ambush, etc.)?",
  "What is a place you should avoid going to?",
  "What do you associate with the desert (or mountains, forest, the sea, the moon, etc.)?",
  "Which is the best planet apart from Earth?",
  "What is important to take with you on a trip through space?",
  "If you lived on another planet, what would you miss most about Earth?",
  "What is a good colour for a car (or shirt, house, shoes, horse, etc.)?",
  "What colour makes a beautiful sunset?",
  "Name something red (or blue, yellow, white, black, grey etc.).",
  "Name someone who people recognize by their first name.",
  "Name a famous fantasy author (or country singer, action movie actor, golfer etc.) ",
  "Name someone famous whose last name begins with T ",
  "What is the best breakfast food?",
  "What kind of food would you be most willing to live on for the rest of your life?",
  "What would you only eat out of politeness and never by choice?",
  "Name a bone in the human body.",
  "Which animal body part would be cool to have as a human?",
  "If you could have one more of any body part, which would you choose?",
  "Which book, movie or video game character would you most like to meet?(or be) ",
  "Who is the most memorable villain from a book or movie?",
  "Name a famous super hero (or ghost, wizard, alien, robot etc.) ",
  "What is the best form of transport?",
  "If you were a super villain, what would your transportation be?",
  "What would be the ideal type of vehicle to combine with a car?",
  "What is the nicest smell?",
  "What is a food that tastes sweet (or sour, salty, bitter, etc.)?",
  "What is something that makes a lot of noise? (or is extremely quiet)",
  "What’s the best fast-food restaurant?",
  "If you could only wear one color forever, what would it be?",
  "What’s the worst vegetable?",
  "Which holiday is the most fun to celebrate?",
  "What’s the best ice cream flavor?",
  "If you had to live in a movie universe, which one would it be?",
  "What’s the most annoying sound in the world?",
  "Which animal is the cutest?",
  "What’s the first thing you’d buy if you won the lottery?",
  "What’s the best dessert?",
  "If you could only have one superpower, what would it be?",
  "What’s the worst thing to find in your sandwich?",
  "Which sport is the most boring to watch?",
  "What’s the most important item to take on a road trip?",
  "If you could visit any city in the world, where would you go?",
  "What’s the best pizza topping?",
  "What’s the best way to spend a lazy Sunday?",
  "Which celebrity would you most want to meet?",
  "What’s the best Disney movie?",
  "What’s the worst household chore?",
  "What’s the best breakfast food?",
  "Which board game is the most fun?",
  "What’s the worst type of weather?",
  "If you could own any car, what would it be?",
  "What’s the best season of the year?",
  "Which drink is the most refreshing?",
  "What’s the best thing to watch on a lazy evening?",
  "If you had to pick one fruit to eat forever, what would it be?",
  "What’s the most annoying thing about mornings?",
  "What’s the best kind of dog?",
  "Which song always gets stuck in your head?",
  "What’s the best way to spend a holiday?",
  "What’s the most iconic video game character?",
  "What’s the best beach activity?",
  "What’s the tastiest fast-food side item?",
  "If you could live in any decade, which one would it be?",
  "What’s the most overrated food trend?",
  "What’s the best way to cook potatoes?",
  "What’s the most useful app on your phone?",
  "What’s the best sport to play?",
  "If you had to live without one modern convenience, what would it be?",
  "What’s the funniest movie you’ve ever seen?",
  "What’s the worst thing to forget on a trip?",
  "What’s the most popular streaming service?",
  "What’s the best kind of soup?",
  "If you could have any animal as a pet, what would it be?",
  "What’s the best kids’ TV show of all time?",
  "What’s the most satisfying snack to eat?",
  "Which type of shoe is the most comfortable?",
  "What’s the best way to celebrate a birthday?",
  "Which country has the best food?",
  "What’s the most iconic candy bar?",
  "What’s the best thing to do on a rainy day?",
  "What’s the worst thing to spill on yourself?",
  "Which emoji do you use the most?",
  "What’s the most relaxing sound?",
  "What’s the worst kind of sandwich?",
  "What’s the best animated movie?",
  "What’s the tastiest type of cake?",
  "What’s the most annoying household sound?",
  "What’s the best way to spend $100?",
  "What’s the most iconic superhero?",
  "What’s the best way to stay cool in summer?",
  "What’s the best kind of chocolate?",
  "What’s the most fun outdoor activity?",
  "Which ice cream topping is the best?",
  "What’s the worst thing about flying?",
  "Which fruit is the most refreshing?",
  "What’s the most interesting landmark in the world?",
  "What’s the best holiday treat?",
  "What’s the worst thing to leave at home?",
  "Which Disney character is the most lovable?",
  "What’s the best carnival food?",
  "What’s the best way to spend a day off?",
  "What’s the most relaxing vacation destination?",
  "What’s the worst smell?",
  "What’s the most nostalgic childhood toy?",
  "What’s the best pasta dish?",
  "What’s the worst thing about winter?",
  "Which animal is the funniest to watch?",
  "What’s the most versatile kitchen tool?",
  "What’s the best way to spend a sunny afternoon?",
  "What’s the best cereal?",
  "What’s the worst mode of transportation?",
  "What’s the best thing to do at the beach?",
  "What’s the most fun holiday decoration?",
  "What’s the worst household task?",
  "Which vegetable is the most delicious?",
  "What’s the best sauce to put on fries?",
  "What’s the best way to end a meal?",
  "What’s the best type of hat?",
  "What’s the worst thing to lose?",
  "What’s the most satisfying chore to finish?",
  "What’s the most interesting zoo animal?",
  "What’s the best way to eat eggs?",
  "What’s the most iconic holiday movie?",
  "What’s the best gift to give someone?",
  "What’s the tastiest cookie?",
  "What’s the best way to enjoy a snowy day?",
  "What’s the worst part of waking up early?",
  "Which classic game show is the best?",
  "What’s the best street food?",
  "What’s the worst type of movie ending?",
  "What’s the most versatile piece of clothing?",
  "What’s the best fruit for a smoothie?",
  "What’s the best thing to eat at a barbecue?",
  "What’s the most overrated TV show?",
  "What’s the best car color?",
  "What’s the best snack for movie night?",
  "What’s the most fun fairground ride?",
  "What’s the most iconic breakfast cereal mascot?",
  "What’s the best flavor of chips?",
  "What’s the most exciting Olympic sport?",
  "What’s the worst song to hear in a store?",
  "What’s the best condiment?",
  "What’s the most creative way to spend $20?",
  "What’s the most comforting meal?",
  "What’s the best soft drink?",
  "Which holiday has the best decorations?",
  "What’s the most popular kind of pie?",
  "What’s the best topping for a burger?",
  "What’s the worst gift to receive?",
  "Which animal is the scariest?",
  "What’s the best breakfast drink?",
  "What’s the best way to spend a Saturday morning?",
  "What’s the most overrated movie genre?",
  "What’s the most iconic book series?",
  "What’s the tastiest thing to eat at a fair?",
  "What’s the best rainy-day activity?",
  "What’s the worst road trip snack?",
  "What’s the most iconic sports team?",
  "What’s the best place to read a book?",
  "What’s the worst thing to forget in the grocery store?",
  "What’s the best thing to grill?",
  "What’s the best car feature?",
  "Which planet would you visit if you could?",
  "What’s the best way to spend an extra hour in the day?",
  "What’s the most relaxing hobby?",
  "What’s the worst type of weather to get caught in?",
  "What’s the best type of cookie?",
  "What’s the most annoying thing about grocery shopping?",
  "What’s the best way to stay warm in winter?",
  "What’s the best smell in the world?",
  "What’s the most iconic childhood snack?",
  "What’s the most overused TV show trope?",
  "What’s the best thing to dip in chocolate?",
  "What’s the best way to travel?",
  "What’s the most underrated holiday?",
  "What’s the worst type of insect?",
  "What’s the best thing to eat for lunch?",
  "What’s the worst flavor of ice cream?",
  "What’s the most fun type of workout?",
  "What’s the best streaming original series?",
  "What’s the most iconic flavor of gum?",
  "What’s the best part of a theme park?",
  "What’s the most relaxing kind of tea?",
  "What’s the worst thing to find in your fridge?",
  "What’s the most iconic breakfast item?",
  "What’s the best gift you’ve ever received?",
  "What’s the best color for a house?",
  "What’s the worst road trip destination?",
  "What’s the best kind of flower to give someone?",
  "What’s the most satisfying dessert?",
  "What’s the worst thing to step on barefoot?",
  "What’s the most fun outdoor sport?",
  "What’s the most iconic movie villain?",
  "What’s the best thing about camping?",
  "What’s the best drink for a hot day?",
  "What’s the worst kind of pizza topping?",
  "What’s the most useful item to have in your kitchen?",
  "What’s the best ice cream cone type?",
  "What’s the most annoying thing about driving?",
  "What’s the best way to relax after a long day?",
  "What’s the best thing to bring to a potluck?",
  "What’s the most overrated candy?",
  "What’s the best fruit to put in a salad?",
  "What’s the most iconic video game of all time?",
  "What’s the best hobby for a rainy day?",
  "What’s the worst way to be woken up?",
  "What’s the best thing to bake in the oven?",
  "What’s the most underrated vegetable?",
  "What’s the most fun thing to do at a park?",
  "What’s the most satisfying flavor of chips?",
  "What’s the best time of day to exercise?",
  "What’s the worst souvenir to bring home?",
  "What’s the best thing to put on toast?",
  "What’s the worst room in the house to clean?",
  "What’s the most iconic animated TV show?",
  "What’s the best topping for a hotdog?",
  "What’s the most overrated breakfast food?",
  "What’s the best color for a car?",
  "What’s the most underrated dessert?",
  "What’s the best thing to do with friends?",
  "What’s the worst thing to wear in the rain?",
  "What’s the most iconic arcade game?",
  "What’s the best thing to eat at a movie theater?",
  "What’s the worst animal to encounter in the wild?",
  "What’s the most comforting soup?",
  "What’s the best way to spend a long weekend?",
  "What’s the worst thing to forget in a school backpack?",
  "What’s the best way to spend a summer evening?",
  "What’s the most relaxing sound in nature?",
  "What’s the most iconic superhero team?",
  "What’s the worst kind of weather to plan an outdoor event?",
  "What’s the best type of bread?",
  "What’s the most underrated form of exercise?",
  "What’s the best kind of muffin?",
  "What’s the most annoying kind of traffic jam?",
  "What’s the best thing to drink when you’re sick?",
  "What’s the worst flavor of soda?",
  "What’s the best thing about the holidays?",
  "What’s the most exciting thing to do at a festival?"
];
