
const spurtdata_theme = [
    "Has fur",
    "Red in color",
    "Released in the 1990s",
    "Written by a female author",
    "Played with a ball",
    "Associated with nature",
    "Capital cities",
    "Known for singing",
    "Spicy",
    "Has stripes",
    "Edible",
    "Lives in water",
    "Can fly",
    "Used in cooking",
    "Found in a forest",
    "Has wheels",
    "Can be worn",
    "Known for dancing",
    "Famous in history",
    "Used in sports",
    "Grows on trees",
    "Has a long tail",
    "Found in space",
    "Can swim",
    "Used as a tool",
    "Made of metal",
    "Known for painting",
    "Fictional characters",
    "Used for writing",
    "Found in the desert",
    "Can climb",
    "Made of wood",
    "Used for cleaning",
    "Found in the ocean",
    "Known for comedy",
    "Found in the jungle",
    "Used in art",
    "Has scales",
    "Can jump",
    "Used for travel",
    "Found in the mountains",
    "Has horns",
    "Used in construction",
    "Found underground",
    "Has feathers",
    "Can glow",
    "Used in gardening",
    "Has a trunk",
    "Made of glass",
    "Found in cities",
    "Can purr",
    "Has sharp teeth",
    "Used in medicine",
    "Has a shell",
    "Can spin",
    "Known for speed",
    "Found in a cave",
    "Can roar",
    "Has claws",
    "Can melt",
    "Found in a meadow",
    "Can bounce",
    "Used for farming",
    "Can grow",
    "Known for strength",
    "Found in a river",
    "Used for hunting",
    "Can run fast",
    "Has whiskers",
    "Can sing",
    "Used for fishing",
    "Can be frozen",
    "Found in a zoo",
    "Can climb trees",
    "Has tusks",
    "Used for shelter",
    "Made of stone",
    "Has an engine",
    "Used in music",
    "Can be eaten raw",
    "Used in war",
    "Can hover",
    "Found in a swamp",
    "Can dig",
    "Has multiple legs",
    "Produces light",
    "Used in transportation",
    "Can be folded",
    "Found on a farm",
    "Used in celebrations",
    "Can regenerate",
    "Has a unique smell",
    "Found in a museum",
    "Can be recycled",
    "Known for wisdom",
    "Used in agriculture",
    "Has a beak",
    "Can carry things",
    "Found in a palace",
    "Can be polished",
    "Grows underground",
    "Used in magic",
    "Can mimic sounds",
    "Has armor",
    "Can survive fire",
    "Can hiss",
    "Found in myths",
    "Has roots",
    "Produces energy",
    "Can live long",
    "Used in storytelling"
  ];
  
  const spurtdata_theme_SK = [
    "Má srsť",
    "Červenej farby",
    "Vydané v 90. rokoch",
    "Napísané ženskou autorkou",
    "Hrá sa s loptou",
    "Spojené s prírodou",
    "Hlavné mestá",
    "Známy spevom",
    "Pikantné",
    "Má pruhy",
    "Jedlé",
    "Žije vo vode",
    "Vie lietať",
    "Používa sa na varenie",
    "Nájdené v lese",
    "Má kolesá",
    "Dá sa nosiť",
    "Známe tancom",
    "Slávne v histórii",
    "Používa sa v športe",
    "Rastie na stromoch",
    "Má dlhý chvost",
    "Nájdené vo vesmíre",
    "Vie plávať",
    "Používa sa ako nástroj",
    "Vyrobené z kovu",
    "Známe maľovaním",
    "Fiktívne postavy",
    "Používa sa na písanie",
    "Nájdené na púšti",
    "Vie šplhať",
    "Vyrobené z dreva",
    "Používa sa na čistenie",
    "Nájdené v oceáne",
    "Známe komédiou",
    "Nájdené v džungli",
    "Používa sa v umení",
    "Má šupiny",
    "Vie skákať",
    "Používa sa na cestovanie",
    "Nájdené v horách",
    "Má rohy",
    "Používa sa v stavebníctve",
    "Nájdené pod zemou",
    "Má perie",
    "Vie svietiť",
    "Používa sa v záhradníctve",
    "Má chobot",
    "Vyrobené zo skla",
    "Nájdené v mestách",
    "Vie priasť",
    "Má ostré zuby",
    "Používa sa v medicíne",
    "Má škrupinu",
    "Vie sa točiť",
    "Známe rýchlosťou",
    "Nájdené v jaskyni",
    "Vie revať",
    "Má pazúry",
    "Vie sa roztopiť",
    "Nájdené na lúke",
    "Vie skákať",
    "Používa sa na farmárčenie",
    "Vie rásť",
    "Známe silou",
    "Nájdené v rieke",
    "Používa sa na lov",
    "Vie rýchlo bežať",
    "Má fúzy",
    "Vie spievať",
    "Používa sa na rybolov",
    "Dá sa zmraziť",
    "Nájdené v zoo",
    "Vie liezť na stromy",
    "Má kly",
    "Používa sa na prístrešie",
    "Vyrobené z kameňa",
    "Má motor",
    "Používa sa v hudbe",
    "Dá sa jesť surové",
    "Používa sa vo vojne",
    "Vie sa vznášať",
    "Nájdené v močarisku",
    "Vie kopať",
    "Má viacero nôh",
    "Vyrába svetlo",
    "Používa sa na dopravu",
    "Dá sa zložiť",
    "Nájdené na farme",
    "Používa sa na oslavy",
    "Vie sa regenerovať",
    "Má jedinečnú vôňu",
    "Nájdené v múzeu",
    "Dá sa recyklovať",
    "Známe múdrosťou",
    "Používa sa v poľnohospodárstve",
    "Má zobák",
    "Vie niesť veci",
    "Nájdené v paláci",
    "Dá sa vyleštiť",
    "Rastie pod zemou",
    "Používa sa v mágii",
    "Vie napodobniť zvuky",
    "Má brnenie",
    "Vie prežiť oheň",
    "Vie syčať",
    "Nájdené v mýtoch",
    "Má korene",
    "Vyrába energiu",
    "Môže žiť dlho",
    "Používa sa v rozprávaní príbehov"
  ];

// const spurtdata_theme = [
//       {"english": "Has fur", "slovak": "Má srsť"},
//       {"english": "Red in color", "slovak": "Červenej farby"},
//       {"english": "Released in the 1990s", "slovak": "Vydané v 90. rokoch"},
//       {"english": "Written by a female author", "slovak": "Napísané ženskou autorkou"},
//       {"english": "Played with a ball", "slovak": "Hrá sa s loptou"},
//       {"english": "Associated with nature", "slovak": "Spojené s prírodou"},
//       {"english": "Capital cities", "slovak": "Hlavné mestá"},
//       {"english": "Known for singing", "slovak": "Známy spevom"},
//       {"english": "Spicy", "slovak": "Pikantné"},
//       {"english": "Has stripes", "slovak": "Má pruhy"},
//       {"english": "Edible", "slovak": "Jedlé"},
//       {"english": "Lives in water", "slovak": "Žije vo vode"},
//       {"english": "Can fly", "slovak": "Vie lietať"},
//       {"english": "Used in cooking", "slovak": "Používa sa na varenie"},
//       {"english": "Found in a forest", "slovak": "Nájdené v lese"},
//       {"english": "Has wheels", "slovak": "Má kolesá"},
//       {"english": "Can be worn", "slovak": "Dá sa nosiť"},
//       {"english": "Known for dancing", "slovak": "Známe tancom"},
//       {"english": "Famous in history", "slovak": "Slávne v histórii"},
//       {"english": "Used in sports", "slovak": "Používa sa v športe"},
//       {"english": "Grows on trees", "slovak": "Rastie na stromoch"},
//       {"english": "Has a long tail", "slovak": "Má dlhý chvost"},
//       {"english": "Found in space", "slovak": "Nájdené vo vesmíre"},
//       {"english": "Can swim", "slovak": "Vie plávať"},
//       {"english": "Used as a tool", "slovak": "Používa sa ako nástroj"},
//       {"english": "Made of metal", "slovak": "Vyrobené z kovu"},
//       {"english": "Known for painting", "slovak": "Známe maľovaním"},
//       {"english": "Fictional characters", "slovak": "Fiktívne postavy"},
//       {"english": "Used for writing", "slovak": "Používa sa na písanie"},
//       {"english": "Found in the desert", "slovak": "Nájdené na púšti"},
//       {"english": "Can climb", "slovak": "Vie šplhať"},
//       {"english": "Made of wood", "slovak": "Vyrobené z dreva"},
//       {"english": "Used for cleaning", "slovak": "Používa sa na čistenie"},
//       {"english": "Found in the ocean", "slovak": "Nájdené v oceáne"},
//       {"english": "Known for comedy", "slovak": "Známe komédiou"},
//       {"english": "Found in the jungle", "slovak": "Nájdené v džungli"},
//       {"english": "Used in art", "slovak": "Používa sa v umení"},
//       {"english": "Has scales", "slovak": "Má šupiny"},
//       {"english": "Can jump", "slovak": "Vie skákať"},
//       {"english": "Used for travel", "slovak": "Používa sa na cestovanie"},
//       {"english": "Found in the mountains", "slovak": "Nájdené v horách"},
//       {"english": "Has horns", "slovak": "Má rohy"},
//       {"english": "Used in construction", "slovak": "Používa sa v stavebníctve"},
//       {"english": "Found underground", "slovak": "Nájdené pod zemou"},
//       {"english": "Has feathers", "slovak": "Má perie"},
//       {"english": "Can glow", "slovak": "Vie svietiť"},
//       {"english": "Used in gardening", "slovak": "Používa sa v záhradníctve"},
//       {"english": "Has a trunk", "slovak": "Má chobot"},
//       {"english": "Made of glass", "slovak": "Vyrobené zo skla"},
//       {"english": "Found in cities", "slovak": "Nájdené v mestách"},
//       {"english": "Can purr", "slovak": "Vie priasť"},
//       {"english": "Has sharp teeth", "slovak": "Má ostré zuby"},
//       {"english": "Used in medicine", "slovak": "Používa sa v medicíne"},
//       {"english": "Has a shell", "slovak": "Má škrupinu"},
//       {"english": "Can spin", "slovak": "Vie sa točiť"},
//       {"english": "Known for speed", "slovak": "Známe rýchlosťou"},
//       {"english": "Found in a cave", "slovak": "Nájdené v jaskyni"},
//       {"english": "Can roar", "slovak": "Vie revať"},
//       {"english": "Has claws", "slovak": "Má pazúry"},
//       {"english": "Can melt", "slovak": "Vie sa roztopiť"},
//       {"english": "Found in a meadow", "slovak": "Nájdené na lúke"},
//       {"english": "Can bounce", "slovak": "Vie skákať"},
//       {"english": "Used for farming", "slovak": "Používa sa na farmárčenie"},
//       {"english": "Can grow", "slovak": "Vie rásť"},
//       {"english": "Known for strength", "slovak": "Známe silou"},
//       {"english": "Found in a river", "slovak": "Nájdené v rieke"},
//       {"english": "Used for hunting", "slovak": "Používa sa na lov"},
//       {"english": "Can run fast", "slovak": "Vie rýchlo bežať"},
//       {"english": "Has whiskers", "slovak": "Má fúzy"},
//       {"english": "Can sing", "slovak": "Vie spievať"},
//       {"english": "Used for fishing", "slovak": "Používa sa na rybolov"},
//       {"english": "Can be frozen", "slovak": "Dá sa zmraziť"},
//       {"english": "Found in a zoo", "slovak": "Nájdené v zoo"},
//       {"english": "Can climb trees", "slovak": "Vie liezť na stromy"},
//       {"english": "Has tusks", "slovak": "Má kly"},
//       {"english": "Used for shelter", "slovak": "Používa sa na prístrešie"},
//       {"english": "Made of stone", "slovak": "Vyrobené z kameňa"},
//       {"english": "Has an engine", "slovak": "Má motor"},
//       {"english": "Used in music", "slovak": "Používa sa v hudbe"},
//       {"english": "Can be eaten raw", "slovak": "Dá sa jesť surové"},
//       {"english": "Used in war", "slovak": "Používa sa vo vojne"},
//       {"english": "Can hover", "slovak": "Vie sa vznášať"},
//       {"english": "Found in a swamp", "slovak": "Nájdené v močarisku"},
//       {"english": "Can dig", "slovak": "Vie kopať"},
//       {"english": "Has multiple legs", "slovak": "Má viacero nôh"},
//       {"english": "Produces light", "slovak": "Vyrába svetlo"},
//       {"english": "Used in transportation", "slovak": "Používa sa na dopravu"},
//       {"english": "Can be folded", "slovak": "Dá sa zložiť"},
//       {"english": "Found on a farm", "slovak": "Nájdené na farme"},
//       {"english": "Used in celebrations", "slovak": "Používa sa na oslavy"},
//       {"english": "Can regenerate", "slovak": "Vie sa regenerovať"},
//       {"english": "Has a unique smell", "slovak": "Má jedinečnú vôňu"},
//       {"english": "Found in a museum", "slovak": "Nájdené v múzeu"},
//       {"english": "Can be recycled", "slovak": "Dá sa recyklovať"},
//       {"english": "Known for wisdom", "slovak": "Známe múdrosťou"},
//       {"english": "Used in agriculture", "slovak": "Používa sa v poľnohospodárstve"},
//       {"english": "Has a beak", "slovak": "Má zobák"},
//       {"english": "Can carry things", "slovak": "Vie niesť veci"},
//       {"english": "Found in a palace", "slovak": "Nájdené v paláci"},
//       {"english": "Can be polished", "slovak": "Dá sa vyleštiť"},
//       {"english": "Grows underground", "slovak": "Rastie pod zemou"},
//       {"english": "Used in magic", "slovak": "Používa sa v mágii"},
//       {"english": "Can mimic sounds", "slovak": "Vie napodobniť zvuky"},
//       {"english": "Has armor", "slovak": "Má brnenie"},
//       {"english": "Can survive fire", "slovak": "Vie prežiť oheň"},
//       {"english": "Can hiss", "slovak": "Vie syčať"},
//       {"english": "Found in myths", "slovak": "Nájdené v mýtoch"},
//       {"english": "Has roots", "slovak": "Má korene"},
//       {"english": "Produces energy", "slovak": "Vyrába energiu"},
//       {"english": "Can live long", "slovak": "Môže žiť dlho"},
//       {"english": "Used in storytelling", "slovak": "Používa sa v rozprávaní príbehov"}
//     ];

const spurtdata_criteria = [
      "Starts with 'A'",
      "Ends with 'B'",
      "Contains 'C'",
      "Does not contain 'D'",
      "Starts with 'E'",
      "Ends with 'F'",
      "Contains 'G'",
      "Does not contain 'H'",
      "Starts with 'I'",
      "Ends with 'J'",
      "Contains 'K'",
      "Does not contain 'L'",
      "Starts with 'M'",
      "Ends with 'N'",
      "Contains 'O'",
      "Does not contain 'P'",
      "Starts with 'Q'",
      "Ends with 'R'",
      "Contains 'S'",
      "Does not contain 'T'",
      "Starts with 'U'",
      "Ends with 'V'",
      "Contains 'W'",
      "Does not contain 'X'",
      "Starts with 'Y'",
      "Ends with 'Z'",
      "Contains 'A'",
      "Does not contain 'B'",
      "Starts with 'C'",
      "Ends with 'D'",
      "Contains 'E'",
      "Does not contain 'F'",
      "Starts with 'G'",
      "Ends with 'H'",
      "Contains 'I'",
      "Does not contain 'J'",
      "Starts with 'K'",
      "Ends with 'L'",
      "Contains 'M'",
      "Does not contain 'N'",
      "Starts with 'O'",
      "Ends with 'P'",
      "Contains 'Q'",
      "Does not contain 'R'",
      "Starts with 'S'",
      "Ends with 'T'",
      "Contains 'U'",
      "Does not contain 'V'",
      "Starts with 'W'",
      "Ends with 'X'",
      "Contains only one syllable",
      "Contains only three letters",
      "Contains only two syllables",
      "Contains only five letters", 
      "Contains double letters",
      "Contains only one vowel", 
      "Contains only two vowels"
    ];

const spurtdata_criteria_SK = [
      "Začína na 'P'",
      "Končí na 'M'",
      "Obsahuje 'C'",
      "Neobsahuje 'D'",
      "Obsahuje 'Č'",
      "Obsahuje 'Ď'",
      "Neobsahuje 'I'",
      "Obsahuje 'F'",
      "Obsahuje 'G'",
      "Neobsahuje 'H'",
      "Obsahuje 'I'",
      "Končí na 'E'",
      "Obsahuje 'Í'",
      "Neobsahuje 'J'",
      "Začína na 'K'",
      "Obsahuje 'Ľ'",
      "Neobsahuje 'B'",
      "Začína na 'N'",
      "Obsahuje 'Ň'",
      "Obsahuje 'O'",
      "Obsahuje 'Ô'",
      "Končí na 'A'",
      "Neobsahuje 'R'",
      "Končí na 'S'",
      "Obsahuje 'Š'",
      "Neobsahuje 'T'",
      "Začína na 'Ť'",
      "Nebsahuje 'U'",
      "Neobsahuje 'A'",
      "Neobsahuje 'V'",
      "Obsahuje 'Y'",
      "Začína na 'Z'",
      "Obsahuje 'Ž'",
      "Obsahuje 'Á'",
      "Neobsahuje 'Č'",
      "Obsahuje 'Š'",
      "Obsahuje iba jednu slabiku",
      "Obsahuje iba tri písmená",
      "Obsahuje iba štyri písmená",
      "Obsahuje iba dve slabiky",
      "Obsahuje iba päť písmen",
      "Obsahuje iba jednu samohlásku",
      "Obsahuje iba dve samohlásky"
    ]
