
const spurtdata_theme = [
    "Has fur",
    "Red in color",
    "Released in the 1990s",
    "Written by a female author",
    "Played with a ball",
    "Associated with nature",
    "Capital cities",
    "Known for singing",
    "Spicy",
    "Has stripes",
    "Edible",
    "Lives in water",
    "Can fly",
    "Used in cooking",
    "Found in a forest",
    "Has wheels",
    "Can be worn",
    "Known for dancing",
    "Famous in history",
    "Used in sports",
    "Grows on trees",
    "Has a long tail",
    "Found in space",
    "Can swim",
    "Used as a tool",
    "Made of metal",
    "Known for painting",
    "Fictional characters",
    "Used for writing",
    "Found in the desert",
    "Can climb",
    "Made of wood",
    "Used for cleaning",
    "Found in the ocean",
    "Known for comedy",
    "Found in the jungle",
    "Used in art",
    "Has scales",
    "Can jump",
    "Used for travel",
    "Found in the mountains",
    "Has horns",
    "Used in construction",
    "Found underground",
    "Has feathers",
    "Can glow",
    "Used in gardening",
    "Has a trunk",
    "Made of glass",
    "Found in cities",
    "Can purr",
    "Has sharp teeth",
    "Used in medicine",
    "Has a shell",
    "Can spin",
    "Known for speed",
    "Found in a cave",
    "Can roar",
    "Has claws",
    "Can melt",
    "Found in a meadow",
    "Can bounce",
    "Used for farming",
    "Can grow",
    "Known for strength",
    "Found in a river",
    "Used for hunting",
    "Can run fast",
    "Has whiskers",
    "Can sing",
    "Used for fishing",
    "Can be frozen",
    "Found in a zoo",
    "Can climb trees",
    "Has tusks",
    "Used for shelter",
    "Made of stone",
    "Has an engine",
    "Used in music",
    "Can be eaten raw",
    "Used in war",
    "Can hover",
    "Found in a swamp",
    "Can dig",
    "Has multiple legs",
    "Produces light",
    "Used in transportation",
    "Can be folded",
    "Found on a farm",
    "Used in celebrations",
    "Can regenerate",
    "Has a unique smell",
    "Found in a museum",
    "Can be recycled",
    "Known for wisdom",
    "Used in agriculture",
    "Has a beak",
    "Can carry things",
    "Found in a palace",
    "Can be polished",
    "Grows underground",
    "Used in magic",
    "Can mimic sounds",
    "Has armor",
    "Can survive fire",
    "Can hiss",
    "Found in myths",
    "Has roots",
    "Produces energy",
    "Can live long",
    "Used in storytelling"
  ];
  
  const spurtdata_theme_SK = [
    "Má srsť",
    "Červenej farby",
    "Vydané v 90. rokoch",
    "Napísané ženskou autorkou",
    "Hrá sa s loptou",
    "Spojené s prírodou",
    "Hlavné mestá",
    "Známy spevom",
    "Pikantné",
    "Má pruhy",
    "Jedlé",
    "Žije vo vode",
    "Vie lietať",
    "Používa sa na varenie",
    "Nájdené v lese",
    "Má kolesá",
    "Dá sa nosiť",
    "Známe tancom",
    "Slávne v histórii",
    "Používa sa v športe",
    "Rastie na stromoch",
    "Má dlhý chvost",
    "Nájdené vo vesmíre",
    "Vie plávať",
    "Používa sa ako nástroj",
    "Vyrobené z kovu",
    "Známe maľovaním",
    "Fiktívne postavy",
    "Používa sa na písanie",
    "Nájdené na púšti",
    "Vie šplhať",
    "Vyrobené z dreva",
    "Používa sa na čistenie",
    "Nájdené v oceáne",
    "Známe komédiou",
    "Nájdené v džungli",
    "Používa sa v umení",
    "Má šupiny",
    "Vie skákať",
    "Používa sa na cestovanie",
    "Nájdené v horách",
    "Má rohy",
    "Používa sa v stavebníctve",
    "Nájdené pod zemou",
    "Má perie",
    "Vie svietiť",
    "Používa sa v záhradníctve",
    "Má chobot",
    "Vyrobené zo skla",
    "Nájdené v mestách",
    "Vie priasť",
    "Má ostré zuby",
    "Používa sa v medicíne",
    "Má škrupinu",
    "Vie sa točiť",
    "Známe rýchlosťou",
    "Nájdené v jaskyni",
    "Vie revať",
    "Má pazúry",
    "Vie sa roztopiť",
    "Nájdené na lúke",
    "Vie skákať",
    "Používa sa na farmárčenie",
    "Vie rásť",
    "Známe silou",
    "Nájdené v rieke",
    "Používa sa na lov",
    "Vie rýchlo bežať",
    "Má fúzy",
    "Vie spievať",
    "Používa sa na rybolov",
    "Dá sa zmraziť",
    "Nájdené v zoo",
    "Vie liezť na stromy",
    "Má kly",
    "Používa sa na prístrešie",
    "Vyrobené z kameňa",
    "Má motor",
    "Používa sa v hudbe",
    "Dá sa jesť surové",
    "Používa sa vo vojne",
    "Vie sa vznášať",
    "Nájdené v močarisku",
    "Vie kopať",
    "Má viacero nôh",
    "Vyrába svetlo",
    "Používa sa na dopravu",
    "Dá sa zložiť",
    "Nájdené na farme",
    "Používa sa na oslavy",
    "Vie sa regenerovať",
    "Má jedinečnú vôňu",
    "Nájdené v múzeu",
    "Dá sa recyklovať",
    "Známe múdrosťou",
    "Používa sa v poľnohospodárstve",
    "Má zobák",
    "Vie niesť veci",
    "Nájdené v paláci",
    "Dá sa vyleštiť",
    "Rastie pod zemou",
    "Používa sa v mágii",
    "Vie napodobniť zvuky",
    "Má brnenie",
    "Vie prežiť oheň",
    "Vie syčať",
    "Nájdené v mýtoch",
    "Má korene",
    "Vyrába energiu",
    "Môže žiť dlho",
    "Používa sa v rozprávaní príbehov"
  ];

const spurtdata_criteria = [
      "Starts with 'A'",
      "Ends with 'B'",
      "Contains 'C'",
      "Does not contain 'D'",
      "Starts with 'E'",
      "Ends with 'F'",
      "Contains 'G'",
      "Does not contain 'H'",
      "Starts with 'I'",
      "Ends with 'J'",
      "Contains 'K'",
      "Does not contain 'L'",
      "Starts with 'M'",
      "Ends with 'N'",
      "Contains 'O'",
      "Does not contain 'P'",
      "Starts with 'Q'",
      "Ends with 'R'",
      "Contains 'S'",
      "Does not contain 'T'",
      "Starts with 'U'",
      "Ends with 'V'",
      "Contains 'W'",
      "Does not contain 'X'",
      "Starts with 'Y'",
      "Ends with 'Z'",
      "Contains 'A'",
      "Does not contain 'B'",
      "Starts with 'C'",
      "Ends with 'D'",
      "Contains 'E'",
      "Does not contain 'F'",
      "Starts with 'G'",
      "Ends with 'H'",
      "Contains 'I'",
      "Does not contain 'J'",
      "Starts with 'K'",
      "Ends with 'L'",
      "Contains 'M'",
      "Does not contain 'N'",
      "Starts with 'O'",
      "Ends with 'P'",
      "Contains 'Q'",
      "Does not contain 'R'",
      "Starts with 'S'",
      "Ends with 'T'",
      "Contains 'U'",
      "Does not contain 'V'",
      "Starts with 'W'",
      "Ends with 'X'",
      "Contains only one syllable",
      "Contains only three letters",
      "Contains only two syllables",
      "Contains only five letters", 
      "Contains double letters",
      "Contains only one vowel", 
      "Contains only two vowels"
    ];

const spurtdata_criteria_SK = [
      "Začína na 'P'",
      "Obsahuje 'P'",
      "Končí na 'M'",
      "Obsahuje 'M'",
      "Obsahuje 'C'",
      "Obsahuje 'D'",
      "Neobsahuje 'D'",
      "Obsahuje 'Č'",
      "Obsahuje 'Ď'",
      "Neobsahuje 'I'",
      "Obsahuje 'F'",
      "Obsahuje 'G'",
      "Neobsahuje 'H'",
      "Obsahuje 'H'",
      "Začína na 'H'",
      "Začína na 'I'",
      "Neobsahuje 'I'",
      "Obsahuje 'I'",
      "Začína na 'R'",
      "Neobsahuje 'R'",
      "Obsahuje 'R'",
      "Končí na 'E'",
      "Neobsahuje 'E'",
      "Obsahuje 'E'",
      "Obsahuje 'Í'",
      "Neobsahuje 'J'",
      "Začína na 'K'",
      "Obsahuje 'K'",
      "Obsahuje 'Ľ'",
      "Neobsahuje 'B'",
      "Obsahuje 'B'",
      "Začína na 'N'",
      "Obsahuje 'N'",
      "Obsahuje 'Ň'",
      "Obsahuje 'O'",
      "Neobsahuje 'O'",
      "Obsahuje 'Ô'",
      "Končí na 'A'",
      "Neobsahuje 'R'",
      "Obsahuje 'R'",
      "Končí na 'S'",
      "Obsahuje 'S'",
      "Neobsahuje 'S'",
      "Začína na 'S'",
      "Obsahuje 'Š'",
      "Neobsahuje 'T'",
      "Začína na 'Ť'",
      "Obsahuje 'U'",
      "Nebsahuje 'U'",
      "Obsahuje 'A'",
      "Neobsahuje 'A'",
      "Začína na 'A'",
      "Neobsahuje 'V'",
      "Obsahuje 'V'",
      "Obsahuje 'Y'",
      "Začína na 'Z'",
      "Obsahuje 'Ž'",
      "Obsahuje 'Á'",
      "Obsahuje 'Č'",
      "Obsahuje 'Š'",
      "Obsahuje iba jednu slabiku",
      "Obsahuje iba tri písmená",
      "Obsahuje iba štyri písmená",
      "Obsahuje iba dve slabiky",
      "Obsahuje iba päť písmen",
      "Obsahuje iba jednu samohlásku",
      "Obsahuje iba dve samohlásky"
    ]
